const mongoose = require("mongoose");

const assessmentSchema = new mongoose.Schema({
  category: String,
  description: mongoose.Mixed,
  id: String,
  head: String,
  image: String,
  name: String,
  price: Number,
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  quantity: Number,
});
const couponSchema = new mongoose.Schema({
  code: String,
  singleUser: mongoose.Mixed,
  status: String,
  usedBy: mongoose.Mixed,
  uses: Number,
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  value: Number,
});

const userSchema = new mongoose.Schema({
  uid: String,
  type: String,
  status: {
    default: "unverifed",
    type: String,
    enum: [
      "unverifed",
      "verified",
      "rejected",
      "pending",
      "restricted",
      "deleted",
    ],
  },
  symptoms: [mongoose.Mixed],
  treatments: [mongoose.Mixed],
  role: String,
  userId: String,
  meetLink: String,
  countryCode: String,
  balance: { type: Number, default: 500 },
  phoneNumber: String,
  alternatePhoneNumber: String,
  email: mongoose.Mixed,
  firstName: String,
  likes: [mongoose.Mixed],
  notifications: [mongoose.Mixed],
  addresses: [
    {
      name: { type: String, required: true },
      phone: { type: String, required: true },
      addressLine1: { type: String, required: true },
      addressLine2: { type: String },
      city: { type: String, required: true },
      state: { type: String, required: true },
      pincode: { type: String, required: true },
      country: { type: String, required: true },
      email: { type: String, required: true },
      landmark: { type: String },
    },
  ],
  bookmarks: [mongoose.Mixed],
  credits: Number,
  instagram: String,
  facebook: String,
  twitter: String,
  github: String,
  linked_in: String,
  address_1: String,
  address_2: String,
  geotag: String,
  isAdmin: mongoose.Mixed,
  maritalStatus: String,
  occupation: String,
  religion: String,
  ethinicity: String,
  stateOfOrigin: String,
  countryOfOrigin: String,
  alternateEmail: String,
  alternateCountryCode: String,
  category: { type: [mongoose.Mixed] },
  dateOfBirth: String,
  displayName: String,
  bloodGroup: String,
  appointments: { type: [mongoose.Mixed] },
  achievements: { type: [mongoose.Mixed] },
  education: { type: [mongoose.Mixed] },
  permissions: { type: [mongoose.Mixed] },
  registration: { type: [mongoose.Mixed] },
  attachments: { type: [mongoose.Mixed] },
  services: { type: [mongoose.Mixed] },
  experience: { type: [mongoose.Mixed] },
  award: { type: [mongoose.Mixed] },
  membership: { type: [mongoose.Mixed] },
  certificates: { type: [mongoose.Mixed] },
  transactions: { type: [mongoose.Mixed] },
  gender: mongoose.Mixed,
  lastName: mongoose.Mixed,
  phone: String,
  organization: mongoose.Mixed,
  venture: mongoose.Mixed,
  bills: [mongoose.Mixed],
  prescriptions: [mongoose.Mixed],
  password: String,
  age: mongoose.Mixed,
  biography: String,
  clinic: mongoose.Mixed,
  clinicTimings: mongoose.Mixed,
  about: String,
  consultation: mongoose.Mixed,
  prefix: String,
  psychotherapy: mongoose.Mixed,
  price: String,
  psychotherapyPrice: String,
  rank: Number,
  platform: mongoose.Mixed,
  psyID: { type: Number },
  roles: { type: [mongoose.Mixed] },
  status: String,
  source: String,
  city: String,
  qr: String,
  otp: String,
  isVenture: { type: Boolean, default: false },
  isClock: { type: Boolean, default: false },
  created: { type: Boolean, default: true },
  group: { type: String },
  yearsOfExperience: String,
  orgName: String,
  country: String,
  title: String,
  photoURL: String,
  pincode: String,
  qualifications: String,
  designation: String,
  courses: mongoose.Mixed,
  instructor: mongoose.Mixed,
  slots: { type: [mongoose.Mixed] },
  specialization: { type: [mongoose.Mixed] },
  state: String,
  workExperience: { type: [mongoose.Mixed] },
  desiredJobTitle: { type: [mongoose.Mixed] },
  skills: { type: [mongoose.Mixed] },
  languages: { type: [mongoose.Mixed] },
  coverLetter: { type: [mongoose.Mixed] },
  expertise: { type: [mongoose.Mixed] },
  currentSalary: { type: String },
  expectedSalary: { type: String },
  deleted: { type: Boolean, default: false },
  deactivated: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const leadSchema = new mongoose.Schema({
  uid: String,
  type: String,
  role: String,
  userId: String,
  meetLink: String,
  countryCode: String,
  phoneNumber: String,
  email: mongoose.Mixed,
  firstName: String,
  credits: Number,
  instagram: String,
  facebook: String,
  twitter: String,
  github: String,
  linked_in: String,
  address_1: String,
  address_2: String,
  geotag: String,
  isAdmin: mongoose.Mixed,
  category: { type: [mongoose.Mixed] },
  dateOfBirth: String,
  displayName: String,
  gender: mongoose.Mixed,
  lastName: mongoose.Mixed,
  phone: String,
  organization: mongoose.Mixed,
  venture: mongoose.Mixed,
  bills: [mongoose.Mixed],
  prescriptions: [mongoose.Mixed],
  password: String,
  age: mongoose.Mixed,
  biography: String,
  clinic: mongoose.Mixed,
  clinicTimings: mongoose.Mixed,
  about: String,
  consultation: mongoose.Mixed,
  prefix: String,
  psychotherapy: mongoose.Mixed,
  price: String,
  psychotherapyPrice: String,
  rank: Number,
  status: String,
  source: String,
  city: String,
  qr: String,
  created: { type: Boolean, default: false },
  yearsOfExperience: String,
  orgName: String,
  country: String,
  title: String,
  photoURL: String,
  pincode: String,
  qualifications: String,
  designation: String,
  courses: mongoose.Mixed,
  instructor: mongoose.Mixed,
  specialization: { type: [mongoose.Mixed] },
  state: String,
  workExperience: { type: [mongoose.Mixed] },
  desiredJobTitle: { type: [mongoose.Mixed] },
  skills: { type: [mongoose.Mixed] },
  languages: { type: [mongoose.Mixed] },
  coverLetter: { type: [mongoose.Mixed] },
  expertise: { type: [mongoose.Mixed] },
  currentSalary: { type: String },
  expectedSalary: { type: String },
  deleted: { type: Boolean, default: false },
  deactivated: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});
const User = mongoose.model("User", userSchema);
const Coupon = mongoose.model("Coupon", couponSchema);
const Assessment = mongoose.model("Assessment", assessmentSchema);
const Lead = mongoose.model("lead", leadSchema);

module.exports = { User, Coupon, Assessment, Lead };
